name: Check OIDC Config

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  exchange:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Request GitHub ID token and exchange for npm
        shell: bash
        run: |
          set -euo pipefail
          ID_TOKEN=$(curl -sS -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=npm:registry.npmjs.org" | jq -r '.value')
          [ -n "${ID_TOKEN:-}" ] && [ "$ID_TOKEN" != "null" ] || { echo "Failed to retrieve GitHub ID token"; exit 1; }
          PKG_RAW=$(jq -r '.name' package.json)
          [ -n "${PKG_RAW:-}" ] && [ "$PKG_RAW" != "null" ] || { echo "Package name missing"; exit 1; }
          PKG=${PKG_RAW//@/%40}; PKG=${PKG//\//%2F}
          echo "$PKG"
          curl -sSf -X POST -H "Authorization: Bearer $ID_TOKEN" "https://registry.npmjs.org/-/npm/v1/oidc/token/exchange/package/$PKG" -d '' >/dev/null
