name: reggi-test-package-001

on:
  push:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # - name: Install npm from npm/oidc branch
        # run: curl -fsSL https://raw.githubusercontent.com/reggi/reggi-test-package/refs/heads/main/install-oidc.sh | bash

      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
