name: reggi-test-package-001

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm from npm/oidc branch
        run: |
          TMP_DIR=$(mktemp -d)
          git clone --depth 1 --single-branch --branch oidc-default-provenance https://github.com/npm/cli.git "$TMP_DIR/cli"
          cd "$TMP_DIR/cli"
          npm install
          npm install -g .
          cd -
          npm config set loglevel silly

      # - name: Create .npmrc file
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc

      - name: Publish
        run: npm publish --provenance
