name: reggi-test-package-001

on:
  push:
    paths-ignore:
      - '.github/workflows/**'
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Up Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install npm from npm/oidc branch
        run: |
          curl -fsSL https://raw.githubusercontent.com/npm/cli/refs/heads/oidc-install/install.sh | bash
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"

      # - name: Create .npmrc file
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc

      - name: Publish
        run: npm publish
